import React from "react"
import { SiGooglemarketingplatform } from "react-icons/si";
import { FaLightbulb } from "react-icons/fa";
import { PiMicrophoneStageFill } from "react-icons/pi";

export const socialMediaHero = {
    title : "SOLUTIONS",
    heading : "AI-Enhanced App Development Solutions",
    context1: "Embarking on a journey to redefine application development, our AI-infused services represent a groundbreaking approach to innovation and client success. At Acumens, we harness the power of artificial intelligence to augment our team of skilled developers, ensuring the delivery of cutting-edge applications that seamlessly blend creativity and functionality.",
    buttonText : "Get An Audit",
    photo : "GettyImages-1370442804-1.webp",
    router:"/audit.htm"
}

export const socialMediaMarktingList = {
    heading : "Optimizing app development with a focus on Return on Investment (ROI).",
    context: "Optimizing app development with a focus on Return on Investment (ROI) involves making strategic decisions throughout the development process to maximize the value generated by the app relative to the resources invested.",
    list : [
        "Market Research",
        "User-Centric Design",
        "Agile Development",
        "Performance Optimization",
        "Effective Marketing Strategy",
        "Regular Updates and Maintenance",
    ]
}

export const socialMediaBlogs = {
    heading : "ACUMENS",
    subHeading : "How our paid Application development service can contribute to the expansion of your revenue",
    blog1 : {header : "Integrating application development with conversion rate optimization (CRO)", context : "Integrating application development with Conversion Rate Optimization (CRO) is a strategic approach that synergizes technical prowess with user-centric optimization. As applications evolve to meet the dynamic needs of users, a seamless incorporation of CRO principles ensures not only functionality but also enhanced user experiences that drive desired actions.", context2 : "By embedding CRO methodologies within the development lifecycle, developers can proactively address user pain points, streamline navigation, and refine user interfaces. This holistic integration cultivates a user-centered design ethos, where data-driven insights gleaned from CRO efforts inform continuous application refinement. The iterative nature of CRO dovetails seamlessly with agile development methodologies, fostering a culture of responsiveness to user feedback and market trends.", photo : "./aiSolutionPictures/pexels-ivan-samkov-8117438-1024x750.webp"},
    blog2 : {header : "Automation and Efficiency", context : "Application development services can automate repetitive tasks, freeing up human resources to focus on more complex and strategic activities. This increased efficiency can lead to cost savings and improved productivity, contributing to overall revenue expansion.", photo : "./aiSolutionPictures/google-experts-1024x750.webp"}
}

export const socialMediaServices = {
    title : "WHAT YOU GET",
    heading : "What does our paid Application development service encompass?",
    subHeading : "By collaborating with Acumens, you unlock access to our comprehensive suite of paid Applications development services. Our offerings are crafted to enhance every aspect of your paid advertising strategy, encompassing",
    card : [
        {title : "Web Application Development", header : "Web Application Development" , context : "Web Application Development Front-end web development: Building the client-side of web applications. Back-end web development: Developing server-side logic and databases."},
        {title : "Remarketing services", header : "Remarketing services" , context : "Remarketing services for application development involve strategies and techniques to re-engage users who have previously interacted with your application or visited your website but did not convert into customers. This can be a powerful way to bring back potential users and encourage them to download or use your application."},
        {title : "AI-Custom App Development", header : "AI-Custom App Development" , context : "By harnessing the capabilities of AI, custom apps can deliver enhanced user experiences, intelligent automation, and data-driven insights. These applications are designed to adapt and evolve, continuously learning from user interactions and refining their functionality over time. AI-driven custom app development enables businesses to streamline processes, optimize decision-making, and stay ahead in today's competitive market."},
        {title : "Security", header : "Security" , context : "Implementing measures to secure the application and user data."},
    ]
}


export const aboutSocialMediaServices = {
    title : "CREATING SUCCESS",
    heading : "What attributes contribute to the effectiveness of our paid Application Development services?",
    card : [
        {icon : React.createElement(PiMicrophoneStageFill), heading : "Quality Assurance", context : "We have dedicated quality assurance (QA) teams that rigorously test applications to identify and fix bugs, ensuring that the final product is reliable and meets the specified requirements.",router:"/app-development.htm"},
        {icon : React.createElement(FaLightbulb), heading : "Security Measures", context : "We have professional development services prioritize the security of your data and the application itself. They implement best practices for secure coding and may conduct security audits to identify and address potential vulnerabilities.",router:"/Seo.htm"},
        {icon : React.createElement(SiGooglemarketingplatform), heading : "Focus on User Experience", context : "Paid services often prioritize user experience (UX) and user interface (UI) design. This results in applications that are intuitive, visually appealing, and user-friendly.",router:"/Email-Marketing.htm"},
    ]
}

export const clientReview = "\"Acumens PPC service is light years ahead of the competition because of their intelligent, specialized and courteous account managers.\""

export const socialMediaProofs = {
    title : "THE PROOF IS IN THE NUMBERS",
    heading : "Why paid search Ads can bring in the numbers",
    cards : [
        {percentage: "38%", context : "of growth rate in brand awareness for businesses that start doing Search Ads"},
        {percentage: "100%", context : "of total clicks on search results page are Search Ads, serving as proof that a dependence on SEO alone limits your potential for more traffic and leads."},
        {percentage: "82%", context : "of clicks on Search Ads are more likely to buy, making for better leads"},
    ]
}

export const socialMediaFaqs = {
    title : "FAQ", 
    heading : "Frequently Asked Questions about App Development Management", 
    subTitle : "Explore our FAQs for valuable insights on managing paid search for your business. If you're interested in paid application development services, delve into our frequently asked questions to gain a better understanding.", 
    faq1 : {
        question : "What is app development management?",
        answer : "App development management refers to the process of planning, organizing, and overseeing the creation of a mobile application. It involves coordinating the efforts of a development team to ensure the successful delivery of a high-quality app within the specified time and budget."
    },
    faq2 : {
        question : "How can risks be identified and mitigated in app development management?",
        answer : "Risk identification involves analyzing potential threats to the project, and mitigation strategies include planning for contingencies, having a risk management plan, and regularly reviewing and updating it."
    },
    faq3 : {
        question : "How do you ensure quality assurance in app development?",
        answer : "Quality assurance involves implementing testing processes throughout the development lifecycle. This includes unit testing, integration testing, user acceptance testing, and performance testing to ensure a high-quality final product."
    },
    faq4 : {
        question : "How do you handle communication within a development team?",
        answer : "Effective communication is crucial for project success. Tools like project management software, regular meetings, and clear documentation help keep team members informed and aligned"
    },
}

export const banner = {
    photo : "./aiSolutionPictures/google-logo.webp",
    heading : "Drive more revenue for your company",
    buttonContext : "Get a Proposal"
}

export const contactMessage = "See how we can help your business grow with digital marketing"
